language: rust
dist: trusty

rust:
  - 1.8.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-all-dev cmake

install:
    - rvm use 2.2
    - gem install construqt-ipaddress
    - gem install jeweler
    - gem install test-unit
    - nvm install 6

script:
    - rvm use 2.2
    - (cd ruby && rake test)
    - (cd rust && cargo build --release --verbose)
    - (cd rust && cargo test --release --verbose)
    - (cd js && npm install && npm test)
    - (cd cpp && cmake -DCMAKE_BUILD_TYPE=Release . && make)
    - ./cpp/test/Release/*/test_crunchy
    - ./cpp/test/Release/*/test_ipaddress
    - ./cpp/test/Release/*/test_ipv4
    - ./cpp/test/Release/*/test_ipv6
    - ./cpp/test/Release/*/test_ipv6_loopback
    - ./cpp/test/Release/*/test_ipv6_mapped
    - ./cpp/test/Release/*/test_ipv6_unspec
    - ./cpp/test/Release/*/test_option
    - ./cpp/test/Release/*/test_prefix128
    - ./cpp/test/Release/*/test_prefix32
    - ./cpp/test/Release/*/test_result
    - ./cpp/test/Release/*/test_rle
