language: rust

rust:
  - 1.8.0

#before_install:
#    - sudo apt-get -qq update
#    - sudo apt-get install -y ruby
install:
    - rvm use ruby-2.0.0-p598
    - gem install rbtree
    - gem install construqt-ipaddress

script:
    - rvm use ruby-2.0.0-p598
    - (cd ruby && rake test)
    - (cd rust && cargo build --verbose)
    - (cd rust && cargo test --verbose)
